---
author: Hüseyin
description: Folyolar
email: huseyin.tekinaslan@bil.omu.edu.tr
url: www.htaslan.com
domain: htaslan.com
brand: '19'
intro: ''
googleanalytics: ''
googleplus: ''
landslide: /usr/bin/landslide
css: _/default.css _/local.css
js: _/default.js
